version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db-config/data:/var/lib/mysql
      - ./db-config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8080:8080"

